Research plan
18F/foia-recommendations pull request #37
Opened 2017-05-18 16:39 UTC by vz3

This addresses issue #13

2017-05-18 23:46 UTC, adborden approved these changes
Looking good.

2017-05-18 23:46 UTC, adborden commented on research-plan.md
> +- How might various FOIA requesters use a national FOIA platform?
I might include the agency perspective. Based on what we've heard and learned so far, I think this is somewhere we can make a dent, even indirectly.

> How might agency processes be improved or enhanced by a national FOIA platform?

2017-05-18 23:46 UTC, adborden commented on research-plan.md
> +- Medium priority (Medium priority)
Typo?

2017-05-18 23:46 UTC, adborden commented on research-plan.md
> +- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?
Awesome questions :sunglasses:

2017-05-19 00:44 UTC, leahbannon requested changes

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- How might we create a platform that increases the quality of FOIA requests?
Perhaps instead of "How might we create a platform that increases the quality of FOIA requests?" we should say "How might we make it easier for the agencies to respond to requests?"

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- How might various FOIA requesters use a national FOIA platform?
and/or benefit from a national FOIA platform?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- Medium priority (Medium priority)
What's this one? :)

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +
What about totally inexperienced users? For example, the basic fact that you are requesting an existing and specific record (and not information about something) is not really intuitive. How are we capturing issues like this?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +
Maybe this should match the categories in our survey?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- Journey map: Mapping how of agencies and requesters think the process works
delete 'of'

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +Note: Avoid detailing project scope until after the interview is complete.
I hadn't thought about this -- I'm glad you pointed it out.

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?
Maybe instead of magic wand, something like, "If you could direct the team to research and fix one problem in the FOIA space..."?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- What percentage of your requests are:
I think some of these might be reported in the annual reports?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- How many documents do you have in your FOIA reading room?
Aren't we gathering this from the surveys?

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- What contributes to an increased request backlog for your agency?
I'm worried this will get into their theories about solutions -- what about something like "What makes a request difficult to fulfill?"

2017-05-19 00:44 UTC, leahbannon commented on research-plan.md
> +- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?
Same comment as for the same question for the requesters.

2017-05-23 15:02 UTC, vz3 commented on research-plan.md
> +- How might various FOIA requesters use a national FOIA platform?
adding in

2017-05-23 15:02 UTC, vz3 commented on research-plan.md
> +- Medium priority (Medium priority)
fixed

2017-05-23 15:02 UTC, vz3 commented on research-plan.md
> +- How might we create a platform that increases the quality of FOIA requests?
added

2017-05-23 15:04 UTC, vz3 commented on research-plan.md
> +- How might various FOIA requesters use a national FOIA platform?
?

2017-05-23 15:04 UTC, vz3 commented on research-plan.md
> +- Medium priority (Medium priority)
fixed

2017-05-23 15:04 UTC, vz3 commented on research-plan.md
> +
added `Individual one-off requesters`

2017-05-23 19:25 UTC, vz3 commented on research-plan.md
> +- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?
I think we get good value out of the magic wand question. It's point is to make interviewees comfortable with thinking blue sky.

2017-05-23 19:26 UTC, vz3 commented on research-plan.md
> +- What percentage of your requests are:
I still think there's value in asking this. We can stop if we feel it's redundant.

2017-05-23 19:26 UTC, vz3 commented on research-plan.md
> +- What contributes to an increased request backlog for your agency?
edited

2017-05-24 15:27 UTC, vz3 commented on research-plan.md
> +Note: Avoid detailing project scope until after the interview is complete.
👍

2017-05-24 15:28 UTC, vz3 commented on research-plan.md
> +
The software categories?

2017-05-24 15:31 UTC, leahbannon approved these changes
I'm good with this once the typo on line 73 is fixed. 👍

2017-05-24 15:31 UTC, leahbannon commented on research-plan.md
> +- Is there a common set of steps
I think this is missing something

2017-05-24 15:31 UTC, leahbannon commented on research-plan.md
> +- What percentage of your requests are:
👍

2017-05-24 17:04 UTC, vz3 commented on research-plan.md
> +- Is there a common set of steps
fixed thanks

2017-05-24 17:04 UTC, vz3 commented on research-plan.md
> +- Is there a common set of steps
https://github.com/18F/foia-recommendations/pull/37/commits/9c29fcea6988c637259eefaf2a1c0019893a70d8

2017-05-24 18:26 UTC, merged